### ISSUE TITLE
first file in input directory skipped by extraction

### ISSUE THREAD

**Issue by euwest** [yola/jsxgettext#5]
if you're extracting, say, `.hbs` messages from `src/js/templates/*.hbs` (via the `trans` keyword in the below example) and the templates dir looks like:

```
templates
  - file-one.hbs
  - file-two.hbs
```

running:

``` sh
function extract_hbs {
    echo "Extracting messages from handlebars:"
    node_modules/.bin/jsxgettext some/output/path \
        --language=handlebars \
        --keyword=trans \
        --join-existing \
        --debug \
        src/js/templates/*.hbs
    echo
}

extract_hbs
```

will not extract messages from `file-one.hbs`.

**Comment by beck** [comment]
Example hbs file?

Also, may be an issue that has been solved upstream (it's been a lot time since merging back in).

**Comment by beck** [comment]
It's been a year and haven't seen this bug happen anywhere else.
